version : "3.7"

services:
    youtube-app:
        image: node:lts-alpine
        build: .
        ports:
            - 3000:3000
        tty: true
        volumes:
            - .:/app
            - /app/node_modules
        working_dir: /app
        command: sh -c "yarn install && yarn start"
